### ISSUE TITLE
Karma exited with code 1 (Brackets 29 on win64)

### ISSUE THREAD

**Issue by joeriks** [artoale/karma-brackets#1]
I run karma with no problem from the console, but cannot start it within the karma-brackets extension. I use chrome with a path to exe setup in CHROME_BIN env var (if that info is something that might help).

**Comment by artoale** [comment]
Thank you very much for the feedback! Yup, unfortunately the brackets embedded nodejs process doesn't run with the user env (there's an issue about that and they're deciding what to do).
In the meantime I could provide some way of forcing env variable via the configuration settings as a workaround...
Unfortunately I'm currently very busy at work and I don't have enough time but I'll work on that as soon as possible!

**Comment by luisrudge** [comment]
The env is not the issue. My karma.conf.js just have the phantomjs browser and karma-brackets still doesn't work. do you need any more info to help you?

**Comment by artoale** [comment]
Mmm, nope, thank you, I probably need a Windows machine to do some tests :)
I don't know how karma launch the PhantomJs process, I'll have a look at
their code first to get a better idea...
 Il giorno 27/ago/2013 03:18, "Luís Rudge" notifications@github.com ha
scritto:

**Comment by artoale** [comment]
@luisrudge, do you have nodejs installed on your PC?

**Comment by artoale** [comment]
Found it, and yes, it's an environment problem...PhantomJS is started (like every other browser) with a default path based on the process.env property (in that case is ProgramFiles, which usually defaults to 'C:\Program Files'. I guess that, since in brackets embedded nodejs process the environment variables are not set, this may cause the problem :(

**Comment by joeriks** [comment]
Its possible to use the full path to the exe, for example:

browsers: ['C:/Program Files (x86)/Google/Chrome/Application/chrome.exe'], 

that also causes "Karma exited with code 1" 

That syntax is however not bug free in Karma, Chrome runs, but with three instances of it. Perhaps the Karma guys fix that soon I dunno.

**Comment by artoale** [comment]
Just to know, are you using the "old" karma.conf.js syntax or the new (0.10) one? The stable branch of this plugin supports the old syntax (I'm working on the new one in another branch, you can test it, if you like to :D)

**Comment by joeriks** [comment]
I'm using 0.10, I am very new to both karma and brackets, will have a deeper look if I get the time, it would be interesting to get into the code and check out how it's done to learn about brackets extensions. Found the branch zip, managed to install it, but it wont start on my win machine (spinning icon keeps spinning).

**Comment by artoale** [comment]
Sorry, my fault - i forgot to mention :) 
You have to install karma globally (`npm install karma -g`) plus the package at https://github.com/artoale/karma-brackets-reporter (again, globally - it's under development so I didn't published it on npm yet).

Btw, in the meantime, you can still create an alternate karma config file with the [old 0.8 format](http://karma-runner.github.io/0.8/config/configuration-file.html) and set which file to use in brackets > file > karma settings.

**Comment by luisrudge** [comment]
Yes, i do have nodejs installed. And karma installed globally. I don't have, however, karma-brackets-reporter. Do you think this is the problem?

**Comment by artoale** [comment]
Yep, but only if you want it to run with the 0.10 version - (in which case
you have to start karma, with 'brackets' in the reporters array, in an
external terminal before starting the brackets internal node server.
I'm of course planning on removing this whole process (and that's why my
0.10 version is not yet published).
In the meantime I suggest you to create a 0.8-compliant configuration file,
as a temporary workaround

2013/8/27 Luís Rudge notifications@github.com

> Yes, i do have nodejs installed. And karma installed globally. I don't
> have, however, karma-brackets-reporter. Do you think this is the problem?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/artoale/karma-brackets/issues/1#issuecomment-23334527
> .

## 

Alessandro Artoni

http://artkiller-web.com

**Comment by luisrudge** [comment]
Ok, thank you! I'll try that!

**Comment by artoale** [comment]
just for information (I' still don't have way to test on win) you can now use this plugin with the new karma syntax - check the instruction in the readme :)

**Comment by julieyuan** [comment]
hmm...Not sure if this one I met is the same issue. I just cannot install Karma Runner extension from Brackets. I follow the steps:
1. Open Brackets > File > Extension Manager (or click on the icon on the sidebar)
2.Select the "Available" tab
3.Search for "karma" and press install

Result: it will report the error below: 
![screen shot 2013-10-09 at 3 17 21 am](https://f.cloud.github.com/assets/4251563/1296619/0c548c4a-30cc-11e3-8a8e-9512f23d6cd0.png)

**Comment by artoale** [comment]
@julieyuan 
That's odd 
Can you please see if you got any more specific error in the console? Are you running Brackets Sprint 31 right?

Btw, if you try to directly download the zip file from the registry ([here](https://s3.amazonaws.com/extend.brackets/karma-brackets/karma-brackets-0.4.1.zip)) and
extract it inside `~\AppData\Roaming\Brackets\extensions\user` we can see if it works.

**Comment by julieyuan** [comment]
@artoale , I got the error log from console. Actually, I run this case with Brackets Sprint 32 (0.32.0-9791) which is an testing build.  

First when I launch Brackets and open the console from Debug>Show Developer Tools, I saw an error in the console. Here is the snapshot: 
![1](https://f.cloud.github.com/assets/4251563/1303293/65c73e84-314f-11e3-8660-03c79f23a583.png)
I am not sure if it relate to this issue， I can install other extensions successfully except karma and another extension. 

Then I download the zip file from the registry and put it into user extension folder, then reload Brackets, it still doesn't work. Here are the snapshot from Extension Manager and console:
![3](https://f.cloud.github.com/assets/4251563/1303303/0b584d20-3150-11e3-8867-f6df8b30bcd5.png)
![2](https://f.cloud.github.com/assets/4251563/1303294/65c88dd4-314f-11e3-9cfb-3802bbbf0064.png)

If this issue relates to Brackets or Karma extension? If it is an Brackets issue, I can file it into Brackets repo. Thanks very much:-)

**Comment by julieyuan** [comment]
I think this issue is more about Brackets, for Sprint31 karma extension can be installed successfully. so file this one in Brackets repo to track it together.

**Comment by artoale** [comment]
I'll try to have a look, but I agree, it looks like a Brackets problem (and
if I remember well they were planning to' change zip implementation)

Il giorno giovedì 10 ottobre 2013, Julie Yuan ha scritto:

> I think this issue is more about Brackets, for Sprint31 karma extension
> can be installed successfully. so file this one in Brackets repo to track
> it together.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/artoale/karma-brackets/issues/1#issuecomment-26025699
> .

## 

Alessandro Artoni

http://artkiller-web.com

**Comment by artoale** [comment]
v 0.4.3 is out and contains this fix!
