### ISSUE TITLE
Brackets IDE

### ISSUE THREAD

**Issue by mentzerj** [artoale/karma-brackets#10]
<blockquote>If the icon in the status bar keep spinning while karma started correctly (browsers opened and with green bar) check if, for some reason, you have a local version of karma installed in node_modules (e.g, if you're using generator-angular for Yeoman that's the case). Even if you run the 'global' karma, plugins will be searched within the local installation. To fix it simply run npm install --save-dev karma-brackets to install the reporter locally and add it to your package.json</blockquote>

This is occuring for my on Mac 10.9.3, Brackets 39, running global.  All tests run/pass work great from terminal, but the icon in the Brackets IDE just spins.  The above work around did not resolve the issue; any other possible solutions?

**Comment by artoale** [comment]
That's rather strange - are you launching an external karma instance or you're starting it from brackets?

**Comment by mentzerj** [comment]
Starting from brackets

**Comment by artoale** [comment]
Should be closed by v 0.5.1! Please, update the extension (and karma-brackets) and let me know if you have any issue!
