### ISSUE TITLE
The downloaded content is not a valid zip file

### ISSUE THREAD

**Issue by opensourceportfolio** [artoale/karma-brackets#4]
Hi, whenever I try to install the extension through the plugin manager I get an error that the installation failed because it's not a valid zip file.

**Comment by artoale** [comment]
Mmm...are you running on win or Mac?

**Comment by opensourceportfolio** [comment]
I'm on Windows.

**Comment by joshbtn** [comment]
Seeing the same issue in sprint 33 and 34

**Comment by artoale** [comment]
The problem unfortunately is linked with brackets zip library... A
temporary workaround is to download the file manually (on brackets registry
https://s3.amazonaws.com/extend.brackets/karma-brackets/karma-brackets-0.4.2.zip)
and extract it inside brackets extension folder, then reload brackets. Let
me know if you have problems...I'll try to fix it as soon as I can!

2013/11/25 Josh Bennett notifications@github.com

> Seeing the same issue in sprint 33 and 34
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/artoale/karma-brackets/issues/4#issuecomment-29216394
> .

## 

Alessandro Artoni

artoale.com

**Comment by DavidFrahm** [comment]
FYI -- Seeing this issue on Mac (10.9) also, with Brackets sprint 34.

**Comment by artoale** [comment]
An issue is open on Brackets to address this issue. It's adobe/brackets/issues/5464.
You may report to them so that they can correct it on Brackets side as fast as possible. I'll try some fix as soon as I can. In the meantime, downloading and extracting in the extension folder should work well enough :)

**Comment by artoale** [comment]
v 0.4.3 is out and contains this fix!
