### ISSUE TITLE
Sorry :(Karma exited with code 8. See the log below for more information

### ISSUE THREAD

**Issue by imtiazwazir** [artoale/karma-brackets#5]
module.js:340
    throw err;
          ^
Error: Cannot find module 'C:\Program Files (x86)\nodejs\node_modules\karma'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:901:3

I am getting this error, OS win8.1

karma and karma-brackets has been installed globally

C:\Users\Imtiaz\AppData\Roaming\npm\karma -> C:\Users\Imtiaz\AppData\Roaming\npm\node_modules\karma\bin\karma
karma@0.10.8 C:\Users\Imtiaz\AppData\Roaming\npm\node_modules\karma
├── di@0.0.1
├── rimraf@2.1.4
├── colors@0.6.0-1
├── graceful-fs@1.2.3
├── mime@1.2.11
├── q@0.9.7
├── chokidar@0.7.1
├── coffee-script@1.6.3
├── lodash@1.1.1
├── minimatch@0.2.14 (sigmund@1.0.0, lru-cache@2.5.0)
├── glob@3.1.21 (inherits@1.0.0)
├── optimist@0.3.7 (wordwrap@0.0.2)
├── useragent@2.0.7 (lru-cache@2.2.4)
├── log4js@0.6.9 (semver@1.1.4, async@0.1.15, readable-stream@1.0.17)
├── connect@2.8.8 (methods@0.0.1, uid2@0.0.2, pause@0.0.1, cookie-signature@1.0.
1, fresh@0.2.0, debug@0.7.4, bytes@0.2.0, qs@0.6.5, buffer-crc32@0.2.1, cookie@0
.1.0, formidable@1.0.14, send@0.1.4)
├── http-proxy@0.10.3 (pkginfo@0.2.3, utile@0.1.7)
└── socket.io@0.9.16 (base64id@0.1.0, policyfile@0.0.4, redis@0.7.3, socket.io-c
lient@0.9.16)

**Comment by imtiazwazir** [comment]
I got it I have to add karma executable from file menu

**Comment by artoale** [comment]
Yup :)
