### ISSUE TITLE
Require and define

### ISSUE THREAD

**Issue by objectkit** [artoale/karma-brackets#6]
Hi there, really getting to like karma-brackets, but now that I've practiced beyond simple Jasmine tests, just wondering if I've missed something- I don't have access to require. Is this a configuration setting I've overlooked? Believe me, I understand there are various vendors of require at the moment, but basically want to test modules and classlets I'm putting together as I check out building extensions for Brackets. Thanks!

**Comment by artoale** [comment]
dear @objectkit , i think you should have a look to http://karma-runner.github.io/0.10/plus/requirejs.html - it provides details on how to setup karma with AMD support. If you are able to run test from the terminal but not from brackets extension, please let me know :)

**Comment by artoale** [comment]
Sorry, just to be sure...running karma from terminal work? I just want to
make sure your whole karma set-up is right. (Eventually, if the
configuration is working, can you provide a minimal example that work on
karma in the terminal but not within brackets?)

On Tue, Feb 4, 2014 at 12:01 PM, David Foley notifications@github.comwrote:

> Hi @artoale https://github.com/artoale, thanks for getting back to me!
> Have a history with JSTestDriver, not karma, but have tried work through of
> examples in the link above... while running in Brackets, I consistently get
> a reference error referring to requirejs... I'm assuming then that the
> dependency is missing. When running from terminal, unfortunately karma
> appears to think of itself as a global, expecting a single workspace in
> which source and test files are kept in. I assume that if I change the file
> paths given to karma init, and point it to my Brackets project, that I
> would break settings for all my projects... am I getting this right?
> Confused! Probably missing something.... thanks!
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/artoale/karma-brackets/issues/6#issuecomment-34052935
> .

## 

Alessandro Artoni

artoale.com

**Comment by objectkit** [comment]
Alessandro, thanks for getting back to me and apologies for the delay- got snowed under with work. Ok, so, following the instructions at the link you supplied, and with a bit of fumbling, I did get an example to work. All I did was essentially quickly create a fake project on my (OSX) desktop, run terminal from that location, went through the steps required for the karma init command. One of the biggest issues was the require configuration stating the baseUrl to be set as 'base/src'. I understand that Karma moves the files to a different filesystem location for testing, but this was detail erroneous to the project. Anyhow, used it, and fine. Next up I opened the same project from within Brackets. As soon as I press File > Start karma server and immediately the Karma log at the bottom states

```
Sorry :(Karma exited with code . See the log below for more information
```

 ... there is no info in the log. Any idea what this could be? Am willing to send you a zip of the mock project I was using if you'd like? Let me know and thanks in advance!

**Comment by artoale** [comment]
Mmm, can you please post your karma.config? Maybe you're missing some
configuration parameter (is karma installed globally only, or is it
installed in your tested project subfolder too (e.g . node_modules folder)?

On Tue, Feb 11, 2014 at 2:59 PM, David Foley notifications@github.comwrote:

> Alessandro, thanks for getting back to me and apologies for the delay- got
> snowed under with work. Ok, so, following the instructions at the link you
> supplied, and with a bit of fumbling, I did get an example to work. All I
> did was essentially quickly create a fake project on my (OSX) desktop, run
> terminal from that location, went through the steps required for the karma
> init command. One of the biggest issues was the require configuration
> stating the baseUrl to be set as 'base/src'. I understand that Karma moves
> the files to a different filesystem location for testing, but this was
> detail erroneous to the project. Anyhow, used it, and fine. Next up I
> opened the same project from within Brackets. As soon as I press File >
> Start karma server and immediately the Karma log at the bottom states
> 
> Sorry :(Karma exited with code . See the log below for more information
> 
> ... there is no info in the log. Any idea what this could be? Am willing
> to send you a zip of the mock project I was using if you'd like? Let me
> know and thanks in advance!
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/artoale/karma-brackets/issues/6#issuecomment-34761866
> .

## 

Alessandro Artoni

artoale.com

**Comment by objectkit** [comment]
Well, here's the karma config to begin (it was initially auto generated by karma init via terminal, running inside the project folder if thats of any use)

```
// Karma configuration
// Generated on Tue Feb 11 2014 13:55:00 GMT+0000 (GMT)

module.exports = function(config) {
config.set({

// base path, that will be used to resolve files and exclude
// why is this empty?
basePath: '',

// frameworks to use
frameworks: ['jasmine', 'requirejs'],

// list of files / patterns to load in the browser
files: [
  {pattern: 'lib/**/*.js', included: false},
  {pattern: 'src/**/*.js', included: false},
  {pattern: 'test/**/*Spec.js', included: false},     
  'test/test-main.js'
],

// list of files to exclude
exclude: [
  'src/main.js'
],

// test results reporter to use
// possible values: 'dots', 'progress', 'junit', 'growl', 'coverage'
reporters: ['progress'],

// web server port
port: 2072,

// enable / disable colors in the output (reporters and logs)
colors: true,

// level of logging
// possible values: config.LOG_DISABLE || config.LOG_ERROR || config.LOG_WARN || config.LOG_INFO || config.LOG_DEBUG
logLevel: config.LOG_INFO,

// enable / disable watching file and executing tests whenever any file changes
autoWatch: true,

// Start these browsers, currently available:
// - Chrome
// - ChromeCanary
// - Firefox
// - Opera (has to be installed with `npm install karma-opera-launcher`)
// - Safari (only Mac; has to be installed with `npm install karma-safari-launcher`)
// - PhantomJS
// - IE (only Windows; has to be installed with `npm install karma-ie-launcher`)
browsers: ['Chrome'],

// If browser does not capture in given timeout [ms], kill it
captureTimeout: 60000,

// Continuous Integration mode
// if true, it capture browsers, run tests and exit
singleRun: false
});
};
```

In terms of configuration parameter... basePath is empty. Is this an implicit relative path, or does it need to be an absolute path? 

There is no nested subfolder within the project named node_modules and I have been working off the assumption that karma was installed globally, but that project paths would be resolved by the extension... if that makes any sense.

Let me know- we are talking green here to a point- new to karma entirely!

UPDATE
Nooooo- I noticed that brackets was missing from reporters. Green light in karma log right now. Will continue to test and post back. Do please feel free to comment on any other mistakes that strike you Allesandro

**Comment by artoale** [comment]
You have to add "brackets" to the list of reporters and install
karma-brackets with npm globally, as stated in the github Readme guide ;)

**Comment by objectkit** [comment]
Double post (I added an update just after sending if you see!)! It still crashes... I start karma server- a momentary error message as listed above, then about a second later, green light 'this is a suite that should run ok'... but when I go to File, Stop Karma Server is greyed out with only Start karma server available to click. Karma was installed via npm... and assuming that also as I can run karma via terminal in any location.

I'll get back to you. A bit confusing.

**Comment by objectkit** [comment]
OK. 

Just let me go and fetch my RTFM brand for my forehead... I had it configured to run on file change- thats why the launch tests command wasn't in the File drop down- even written in under Usage, step 6 bonus. Doh! Case closed- thanks- now- off to break some more things....

**Comment by artoale** [comment]
Ok! I'll try to improve the docs, thanks for reporting!

On Tue, Feb 11, 2014 at 3:35 PM, David Foley notifications@github.comwrote:

> OK.
> 
> Just let me go and fetch my RTFM brand for my forehead... I had it
> configured to run on file change- thats why the launch tests command wasn't
> in the File drop down- even written in under Usage, step 6 bonus. Doh! Case
> closed- thanks- now- off to break some more things....
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/artoale/karma-brackets/issues/6#issuecomment-34765637
> .

## 

Alessandro Artoni

artoale.com

**Comment by objectkit** [comment]
No worries, and thanks for helping me get on the right path :)
