### ISSUE TITLE
Sorry :(Karma exited with code 0) -  but no log

### ISSUE THREAD

**Issue by OrenMeron** [artoale/karma-brackets#9]
Hello I am trying to use the karma brackets extension with no success.
![brakets](https://f.cloud.github.com/assets/6782316/2257487/6f46294c-9e1a-11e3-8018-bb681487c3e8.png)

As shown in the screen shot, karma exited with code 0 but there is no log showing.
I followed the installation guide step by step.
Hope to hear from you soon
    thanks
     mmy

**Comment by artoale** [comment]
You 're running karma in a project without a karma.conf.js file :) 
Please, have a look at the README, you have to install karma and karma-brackets (either both locally or both globally) and add "brackets"  in the reporter list.

Let me know :)

**Comment by OrenMeron** [comment]
I added the conf file to the karma settings in brackets, and i added  "brackets" in the reporter list.
I think i installed both globally but i will check again.
Can you think about something else that can cause this?
  Thanks again
     mmy

**Comment by artoale** [comment]
Are you able to run karma from the command line normally? If yes, can you
please paste the output here?

On Tue, Feb 25, 2014 at 2:54 PM, mtzMMY notifications@github.com wrote:

> I added the conf file to the karma settings in brackets, and i added
> "brackets" in the reporter list.
> I think i installed both globally but i will check again.
> Can you think about something else that can cause this?
> Thanks again
> mmy
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/artoale/karma-brackets/issues/9#issuecomment-36015112
> .

## 

Alessandro Artoni

artoale.com

**Comment by OrenMeron** [comment]
Yes it works fine from command line...
![karma](https://f.cloud.github.com/assets/6782316/2258773/35d7a2b8-9e2d-11e3-9cda-215cbccf62a5.png)

**Comment by OrenMeron** [comment]
This is how my karma settings looks like

![karma_set](https://f.cloud.github.com/assets/6782316/2258851/45b637e8-9e2e-11e3-8565-1b61644cecd7.png)

**Comment by artoale** [comment]
Ok, can I ask you for 2 further thing? When karma is started from brackets,
it is run from the current project within brackets, but according to the
screenshot you sent me, the current project doesn't contain any
karma-related file. Try to run everything after opening the phonecat folder
in brackets. If it doesn't work, please send me your config file, just to
be sure :)

On Tue, Feb 25, 2014 at 3:05 PM, mtzMMY notifications@github.com wrote:

> This is how my karma settings looks like
> 
> [image: karma_set]https://f.cloud.github.com/assets/6782316/2258851/45b637e8-9e2e-11e3-8565-1b61644cecd7.png
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/artoale/karma-brackets/issues/9#issuecomment-36016382
> .

## 

Alessandro Artoni

artoale.com

**Comment by Shiftyy** [comment]
Hi,

I've got trouble with the same issue.
In Brackets I get the message "Sorry :(Karma exited with code 0. See the log below for more information" but no Log is visible.

When starting Karma with this karma.conf.js via grunt-task it works just fine.

![unbenannt](https://cloud.githubusercontent.com/assets/7113491/2565192/537dfc98-b8b0-11e3-83f1-183a9c7c8b58.png)

Any idea how to fix that?

**Comment by artoale** [comment]
Can you please post your karma.conf.js?

**Comment by Shiftyy** [comment]
![unbenannt](https://cloud.githubusercontent.com/assets/7113491/2565359/3fae1fba-b8b3-11e3-8697-3d32c24d2178.png)

**Comment by artoale** [comment]
Do you have a local copy of karma installed? (in the node_module folder)
If yes, you shoud make sure you ave both karma AND karma-brackets installed
locally. If not, make sure to have both installed globally :)

**Comment by Shiftyy** [comment]
I tried with both installed local and both installed global.
Still having the same issue ... :(

**Comment by Uter1007** [comment]
Same error here :( Using newest Brackets (0.39)

**Comment by artoale** [comment]
Should be closed by v 0.5.1! Please, update the extension (and karma-brackets) and let me know if you have any issue!
